main/urls.py
from django.conf.urls import url
from django.urls import path, include
from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView, PasswordChangeDoneView, PasswordResetDoneView,\
    PasswordResetCompleteView

import main.views.views_error
from main.views.views_upload_old import batch_upload
import main.views.views_admin as v_admin
import main.views.views_autocomplete as v_autocomplete
import main.views.views_browse as v_browse
import main.views.views_edit as v_edit
import main.views.views_export as v_export
import main.views.views_info as v_info
import main.views.views_messages as v_messages
import main.views.views_news as v_news
import main.views.views_search as v_search
import main.views.views_subscriptions as v_subscriptions
import main.views.views_upload as v_upload
import main.views.views_user as v_user
import main.views.views_api as v_api


app_name = 'main'
urlpatterns = [
    # ROOT VIEW
    path('', v_info.start_view, name='start'),
    path('set_language/<str:language>/', v_info.set_language_view, name='set_tr_language'),

    ##############
    # INFO PAGES
    path('info/', TemplateView.as_view(template_name='main/info/blank.html'), name='info'),
    path('info/instructions/', v_info.guidelines_view, name='guidelines'),
    path('info/tos/',        TemplateView.as_view(template_name='main/info/tos.html'),        name='tos'),
    path('info/about/',      TemplateView.as_view(template_name='main/info/about.html'),      name='about'),
    path('info/contact/', v_info.contact_view, name='contact'),
    path('info/faq/', TemplateView.as_view(template_name='main/info/faq.html'), name='faq'),
    path('info/unsubscribe/', v_info.unsubsribe_newsletter_view, name='unsubscribe_newsletter'),

    ##############
    # SEARCH VIEW
    # path('search/', v_search.SearchView.as_view(), name='search'),
    path('search/', v_search.transcriptiones_search, name='search'),
    path('search_redirect/', v_search.search_box_redirect, name='search_redirect'),

    ##############
    # News VIEW
    path('news/', v_news.news_view, name='news'),

    ##############
    # UPLOAD PAGES
    path('upload/options/', v_upload.upload_options, name='upload_options'),
    # Upload form for a new document
    path('upload/document/', v_upload.upload_transcription_view, name='upload_document'),
    # Upload form for a new document
    # path('upload/documents/', v_upload.upload_multiple_transcriptions_view, name='upload_multiple'),
    # Contact form for a batch upload
    path('upload/batch/', v_upload.upload_batch_view, name='upload_batch'),
    # Thank you screen after uploading
    path('upload/thanks/<int:doc_id>', v_upload.thanks_view, name='thank_you'),

    ##############
    # AUTOCOMPLETE VIEWS
    url(r'^inst-autocomplete/$', v_autocomplete.InstitutionAutocomplete.as_view(), name='inst-autocomplete', ),
    path('inst-autocomplete-id/', v_autocomplete.institution_id_view, name='inst-autocomplete-id', ),
    url(r'^refn-autocomplete/$', v_autocomplete.RefNumberAutocomplete.as_view(), name='refn-autocomplete', ),
    path('refn-autocomplete-id/', v_autocomplete.refnumber_id_view, name='refn-autocomplete-id', ),
    url(r'^srctype-autocomplete/$', v_autocomplete.SourceTypeAutocomplete.as_view(), name='srctype-autocomplete', ),
    url(r'^srctype-ch-autocomplete/$', v_autocomplete.SourceTypeChildAutocomplete.as_view(), name='srctype-ch-autocomplete', ),
    url(r'^author-autocomplete/$', v_autocomplete.AuthorAutocomplete.as_view(create_field='author_name'), name='author-autocomplete', ),
    url(r'^language-autocomplete/$', v_autocomplete.LanguageAutocomplete.as_view(), name='language-autocomplete', ),

    ##############
    # VIEW DATA PAGES
    path('display/', v_browse.browse_options, name='browse_options'),

    path('display/institutions/', v_browse.InstitutionListView.as_view(), name='institution_list'),
    path('display/institutions/<slug:inst_slug>/', v_browse.InstitutionDetailView.as_view(), name='institution_detail'),
    path('display/institutions/<slug:inst_slug>/<slug:ref_slug>/', v_browse.RefNumberDetailView.as_view(), name='ref_number_detail'),
    path('display/institutions/<slug:inst_slug>/<slug:ref_slug>/<slug:doc_slug>/', v_browse.DocumentDetailView.as_view(), name='document_detail'),
    path('display/institutions/<slug:inst_slug>/<slug:ref_slug>/<slug:doc_slug>/<int:version_nr>/', v_browse.DocumentDetailView.as_view(), name='document_legacy_detail'),
    path('display/institutions/<slug:inst_slug>/<slug:ref_slug>/<slug:doc_slug>/history/', v_browse.DocumentHistoryView.as_view(), name='document_history'),
    path('display/institutions/<slug:inst_slug>/<slug:ref_slug>/<slug:doc_slug>/export/', v_export.DocumentExportView.as_view(), name='document_export'),

    path('display/source_types/', v_browse.source_type_list_view, name='source_type_list'),
    path('display/source_types/<int:pk>/', v_browse.source_type_detail_view, name='source_type_detail'),
    path('display/source_types/<int:pk>/all/', v_browse.source_type_group_detail_view, name='source_type_group_detail'),

    path('display/scribes/', v_browse.AuthorListView.as_view(), name='author_list'),
    path('display/scribes/<int:pk>/', v_browse.AuthorDetailView.as_view(), name='author_detail'),

    path('insti_idx/', v_upload.upload_transcription_view, name='index_inst'),
    path('instis/create/', v_upload.ModalCreateInstitutionView.as_view(), name='create_inst'),
    path('refis/create/', v_upload.ModalCreateRefNumberView.as_view(), name='create_refn'),
    path('instis/', v_upload.institution_dropdown_view, name='insts'),
    path('refis/', v_upload.refnumber_dropdown_view, name='refns'),

    ##############
    # USER VIEWS
    path('user/signup/', v_user.signup, name='signup'),
    path('user/activationsent/', v_user.AccountActivationSentView.as_view(), name='account_activation_sent'),
    path('user/activate/<uidb64>/<token>/', v_user.show_activation_page, name='activate'),
    path('user/activate/', v_user.activate, name='activate_user'),
    path('user/login/', v_user.CustomLoginView.as_view(), name='login'),
    path('user/logout/', LogoutView.as_view(template_name='main/users/logout.html'), name='logout'),
    path('user/passwordchange/', v_user.CustomPasswordChangeView.as_view(), name='password_change'),
    path('user/passwordchange/done/', PasswordChangeDoneView.as_view(template_name='main/users/password_change_done.html'), name='password_change_done'),
    path('user/profile/', v_user.userprofile, name='profile'),
    path('user/documents/', v_user.my_documents, name='my_documents'),
    path('user/documents/created/', v_user.my_documents, name='my_own_documents'),
    path('user/documents/drafts/', v_user.my_documents, name='my_document_drafts'),
    path('user/public/profile/<str:username>/', v_user.public_profile, name='public_profile'),
    path('user/profile/update/', v_user.UserUpdateView.as_view(), name='user_update'),
    path('user/profile/email_update/', v_user.change_email_view, name='user_email_update'),
    path('user/passwordreset/', v_user.CustomPasswordResetView.as_view(), name='password_reset'),
    path('user/passwordreset/done/', PasswordResetDoneView.as_view(template_name='main/users/password_reset_done.html'), name='password_reset_done'),
    path('user/reset/<uidb64>/<token>/', v_user.CustomPasswordConfirmView.as_view(), name='password_reset_confirm'),
    path('user/reset/done/', PasswordResetCompleteView.as_view(template_name='main/users/password_reset_complete.html'), name='password_reset_complete'),
    path('user/usernamerequest/', v_user.request_username_view, name='username_request'),
    path('user/usernamerequest/done', v_user.request_username_done_view, name='username_request_done'),
    path('user/emailchange/done', v_user.request_email_change_done_view, name='change_email_request_done'),

    ##############
    # USER SUBSCRIPTIONS
    path('user/subscriptions/', v_subscriptions.subscriptions, name='subscriptions'),
    path('subscribe/institution/<int:pk>/', v_subscriptions.subscribe_institution_view, name='subscribe_institution'),
    path('subscribe/ref_number/<int:pk>/', v_subscriptions.subscribe_ref_number_view, name='subscribe_ref_number'),
    path('subscribe/document/<int:pk>/', v_subscriptions.subscribe_document_view, name='subscribe_document'),
    path('subscribe/user/<int:pk>/', v_subscriptions.subscribe_user_view, name='subscribe_user'),
    path('subscribe/scribe/<int:pk>/', v_subscriptions.subscribe_author_view, name='subscribe_author'),
    path('unsubscribe/institution/<int:pk>/', v_subscriptions.unsubscribe_institution_view, name='unsubscribe_institution'),
    path('unsubscribe/ref_number/<int:pk>/', v_subscriptions.unsubscribe_ref_number_view, name='unsubscribe_ref_number'),
    path('unsubscribe/document/<int:pk>/', v_subscriptions.unsubscribe_document_view, name='unsubscribe_document'),
    path('unsubscribe/user/<int:pk>/', v_subscriptions.unsubscribe_user_view, name='unsubscribe_user'),
    path('unsubscribe/scribe/<int:pk>/', v_subscriptions.unsubscribe_author_view, name='unsubscribe_author'),
    path('unsubscribe/all/', v_subscriptions.unsubscribe_all_view, name='unsubscribe_all'),

    ##############
    # USER MESSAGES & NOTIFICATIONS
    path('user/messages/', v_messages.messages_view, name='messages'),
    path('user/messages/delete/all', v_messages.delete_all_messages_view, name='messages_delete_all'),
    path('user/messages/delete/<str:message_type>/<int:message_id>', v_messages.messages_delete_view, name='messages_delete'),
    path('user/messages/view/<str:message_type>/<int:message_id>/', v_messages.messages_read_view, name='messages_read'),
    path('user/messages/reply/<int:message_id>/', v_messages.messages_reply_view, name='messages_reply'),
    path('user/messages/unread/<str:message_type>/<int:message_id>/', v_messages.messages_mark_unread_view, name='messages_mark_unread'),

transcriptiones/urls.py
"""transcriptiones URL Configuration
1. '' points to the main transcriptiones web app
2. 'admin' points to the Django administration interface
3. 'i18n' points to the language selection views

"""
from django.contrib import admin
from django.urls import include, path

handler404 = 'main.views.views_error.custom_page_not_found_view'
handler500 = 'main.views.views_error.custom_error_view'
handler403 = 'main.views.views_error.custom_permission_denied_view'
handler400 = 'main.views.views_error.custom_bad_request_view'

urlpatterns = [
    path('',  include('main.urls')),
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    ]

main/views.py
from django.shortcuts import render, get_object_or_404
from django.utils.safestring import mark_safe
from django.utils.translation import ugettext as _
from django.views.generic import DetailView, ListView, View
from django.views.generic.detail import SingleObjectMixin
from django_tables2 import SingleTableMixin, MultiTableMixin

from .models import Institution, RefNumber, Document
from .tables import TitleValueTable, RefNumberTable, DocumentTable


class InstitutionListView(ListView):
    """Creates a list view for all instituions. """
    model = Institution
    queryset = Institution.objects.order_by('city', 'institution_name')
    template_name = "main/lists/institution_list.html"
    context_object_name = "institutions"


class InstitutionDetailView(MultiTableMixin, DetailView):
    """View to show details of institutions and list all reference numbers of this institution"""
    model = Institution
    slug_field = 'institution_slug'
    slug_url_kwarg = 'inst_slug'

    table_pagination = {
        "per_page": 20
    }

    template_name = "main/details/institution_detail.html"

    def get_tables(self):
        institution = self.get_object()
        data = [
            {'title': institution._meta.get_field('street').verbose_name,
             'value': institution.street},
            {'title': f"{institution._meta.get_field('zip_code').verbose_name} / {institution._meta.get_field('city').verbose_name}",
             'value': f"{institution.zip_code} / {institution.city}"},
            {'title': institution._meta.get_field('country').verbose_name,
             'value': institution.country.name},
            {'title': institution._meta.get_field('site_url').verbose_name,
             'value': mark_safe(f'<a href="{institution.site_url}" target="_blank">{institution.site_url}</a>')}
        ]

        tables = [
            TitleValueTable(data=data),
            RefNumberTable(RefNumber.objects.filter(holding_institution=institution))
        ]
        return tables


class RefNumberDetailView(MultiTableMixin, DetailView):
    """View to show details of institutions and list all reference numbers of this institution"""

    model = RefNumber
    slug_field = 'ref_number_slug'
    slug_url_kwarg = 'ref_slug'

    table_pagination = {
        "per_page": 20
    }

    template_name = "main/details/ref_number_detail.html"


    def get_tables(self):
        ref_number = self.get_object()
        data = [
            {'title': ref_number._meta.get_field('holding_institution').verbose_name,
             'value': ref_number.holding_institution},
            {'title': ref_number._meta.get_field('ref_number_name').verbose_name,
             'value': ref_number.ref_number_name},
            {'title': ref_number._meta.get_field('ref_number_title').verbose_name,
             'value': ref_number.ref_number_title},
            {'title': ref_number._meta.get_field('collection_link').verbose_name,
             'value': mark_safe(f'<a href="{ref_number.collection_link}" target="_blank">{ref_number.collection_link}</a>')}
        ]

        tables = [
            TitleValueTable(data=data),
            DocumentTable(Document.objects.filter(parent_ref_number=ref_number)),
        ]
        return tables


class DocumentDetailView(MultiTableMixin, DetailView):
    """View to display DocumentTitle. Accepts optional version number to display legacy version"""
    model = Document
    slug_field = 'document_slug'
    slug_url_kwarg = 'doc_slug'

    template_name = "main/details/document_detail.html"

    def get_object(self):
        institution = self.kwargs.get('inst_slug')
        ref_number = self.kwargs.get('ref_slug')
        document = self.kwargs.get('doc_slug')

        queryset = Document.all_objects.filter(parent_institution__institution_slug=institution)
        queryset = queryset.filter(parent_ref_number__ref_number_slug=ref_number)
        queryset = queryset.filter(document_slug=document)

        # if url specifies version_number, get this specific version, else get the active version
        if 'version_nr' in self.kwargs:
            version = self.kwargs.get('version_nr')
        else:
            version = queryset.get(active=True).version_number

        return get_object_or_404(queryset, version_number=version)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # if view should display legacy version, add newest version to context
        if 'version_nr' in self.kwargs:
            newest = self.get_object().get_versions().latest()
            context['newest'] = newest

        return context

    def get_tables(self):
        document = self.get_object()
        data = document.get_card_data()

        tables = [TitleValueTable(data=data[i]) for i in range(len(data))]

        return tables


def test(request):
    return render(request, 'main/test.html')

main/views/views_error.py
from django.shortcuts import render


def custom_page_not_found_view(request, exception=None):
    return render(request, "main/errors/404.html", {})

def custom_error_view(request, exception=None):
    return render(request, "main/errors/500.html", {})

def custom_permission_denied_view(request, exception=None):
    return render(request, "main/errors/403.html", {})

def custom_bad_request_view(request, exception=None):
    return render(request, "main/errors/400.html", {})

main/views/views_news.py
from django.shortcuts import render
from main.models import NewsMessage


def news_view(request):
    news_data = NewsMessage.objects.all().order_by('-news_time')
    return render(request, "main/news/news_view.html", {'news_data': news_data})

main/templates/main/users/account_activation_invalid.html
{% extends 'main/base.html' %}
{% load i18n %}
{% load transcriptiones %}
{% load django_bootstrap_breadcrumbs %}

{% block page_title %}
    {% translate 'Login' %}
{% endblock %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb _("Login") "" %}
{% endblock %}

{% block content %}
    {% card 'info_card' _('Invalid Link') %}
    <div class="text-center">
        {% translate 'This activation link is invalid.' %}
    </div>
    {% endcard %}
{% endblock %}

main/templates/main/users/account_activation_sent.html
{% extends 'main/base.html' %}
{% load i18n %}
{% load transcriptiones %}
{% load django_bootstrap_breadcrumbs %}

{% block page_title %}
    {% translate 'Login' %}
{% endblock %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb _("Login") "" %}
{% endblock %}

{% block content %}
    {% card 'info_card' _('Registration Email Sent') %}
    <div class="text-center">
        {% translate 'You have been successfully registered. You will receive a confirmation email shortly.' %}
    </div>
    {% endcard %}
{% endblock %}

main/templates/main/users/accountactivationemail.html
{% autoescape off %}
Sehr geehrte*r {{ user.username }},

Herzlich Willkommen auf {{ domain }}. Klicken Sie auf den untenstehenden Link um die Registrierung abzuschliessen.

http://{{ domain }}{% url 'main:activate' uidb64=uid token=token %}

{% endautoescape %}

main/templates/main/users/password_change.html
{% extends 'main/base.html' %}
{% load static %}
{% load i18n %}
{% load transcriptiones %}
{% load crispy_forms_tags %}
{% load django_bootstrap_breadcrumbs %}

{% block page_title %}
    {% translate 'Change Password' %}
{%  endblock %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Users" "" %}
    {% breadcrumb request.user.username "main:profile" %}
    {% breadcrumb _('Change Password') '' %}
{% endblock %}

{% block content %}

    {% include 'main/users/user_options.html' %}

    {% card 'change_password' _('Change Your Password') %}
        <form method="post" action="{% url 'main:password_change' %}">
            {% csrf_token %}
            {% for field in form %}
                {{ field|as_crispy_field }}
            {% endfor %}
            <label for="the_save_button" class="col-form-label col-sm-3">
                &nbsp;
            </label>
            <button type="submit" class="btn btn-primary">{%  translate 'Change Password' %}</button>
        </form>
    {% endcard %}

{% endblock %}

main/templates/main/users/password_change_done.html
{% extends 'main/base.html' %}
{% load i18n %}
{% load transcriptiones %}
{% load django_bootstrap_breadcrumbs %}

{% block page_title %}
    {% translate 'Password changed' %}
{%  endblock %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb request.user.username "main:profile" %}
    {% breadcrumb _("Change password") "main:password_change" %}
{% endblock %}


{% block content %}
    {% card 'pw_changed_card' _('Password Changed') %}
        <div class="text-center">
            {% translate 'Your password has been sucessfully changed.' %}<br/><br/>
            <a href="{% url 'main:start' %}" class="btn btn-primary" role="button">{% translate 'Go back to main page' %}</a>
        </div>
    {% endcard %}
{% endblock %}

main/templates/main/users/password_reset_complete.html
{% extends 'main/base.html' %}
{% load i18n %}
{% load transcriptiones %}
{% load django_bootstrap_breadcrumbs %}

{% block page_title %}
    {% translate 'Password Reset' %}
{%  endblock %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb _("Reset Password") "" %}
{% endblock %}

{% block content %}

    {% card 'reset_done_card' _('Your Password Has Been Reset') %}
         <div class="text-center">
            <p>{% translate 'Your password has been reset successfully.' %}</p>
            <a href="{% url 'main:login' %}" class="btn btn-primary">{% translate 'Login' %}</a>
        </div>
    {% endcard %}

{% endblock %}

main/templates/main/users/password_reset_done.html
{% extends 'main/base.html' %}
{% load i18n %}
{% load transcriptiones %}
{% load django_bootstrap_breadcrumbs %}

{% block page_title %}
    {% translate 'Password Reset' %}
{%  endblock %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb _("Reset Password") "" %}
{% endblock %}

{% block content %}

    {% card 'reset_done_card' _('Your Password Has Been Reset') %}
        {% translate "Your password has been reset successfully. You will receive an email with a reset link shortly." %}
    {% endcard %}

{% endblock %}

main/templates/main/users/passwordchangedone.html
{% extends 'base.html' %}

{% block content %}

<div>Ihr Passwort wurde erfolgreich geändert.</div>

{% endblock %}

main/templates/main/users/passwordresetconfirm.html
{% extends 'base.html' %}

{% load static %}

{% block dependencies %}
<!-- Tooltipster Plugin -->
<script src="{% static 'base/vendor/tooltipster/dist/js/tooltipster.bundle.js' %}"></script>
<link rel="stylesheet" href="{% static 'base/vendor/tooltipster/dist/css/tooltipster.bundle.css' %}" />
<link rel="stylesheet" href="{% static 'base/vendor/tooltipster/dist/css/plugins/tooltipster/sideTip/themes/tooltipster-sideTip-punk.min.css' %}" />
{% endblock dependencies %}

{% block content %}

<h2>Neues Passwort setzen</h2>
<form method="post">
    {% csrf_token %}
    {% for field in form %}
    <div class="fieldWrapper form-group row">
        <div class="col-sm-4">
            <label for="{{ field.id_for_label }}" class="control-label">
                {{ field.label }}
                <i class="fas fa-info-circle tooltipster" data-tooltip-content="#tt_{{ field.name|cut:"new_" }}"></i>
            </label>
        </div>
        <div class="col-sm-8">
            {{ field }}
        </div>
    </div>
    {% for error in field.errors %}
    <p style="color: red">{{ error }}</p>
    {% endfor %}
    {% endfor %}
    <button type="submit" class="btn btn-secondary">Passwort neu setzen</button>
</form>

{% include "main/users/tooltips.html" %}

{% endblock %}

{% block javascript %}
<script src="{% static 'users/userscripts.js' %}"></script>
{% endblock javascript %}

main/templates/main/users/passwordresetemail.html
Jemand hat versucht das Passwort für den Account mit der E-Mail-Adresse {{ email }} zurückzusetzen.
Folgen Sie dem untenstehenden Link um ein neues Passwort zu setzen.
{{ protocol}}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

main/templates/main/users/read_message.html
{% extends 'main/base.html' %}
{% load static %}
{% load i18n %}
{% load transcriptiones %}
{% load render_table from django_tables2 %}
{% load django_bootstrap_breadcrumbs %}
{% load crispy_forms_tags %}

{% block page_title %}
    {% translate 'Read Message' %}
{%  endblock %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb _('Users') "" %}
    {% breadcrumb request.user.username "main:profile" %}
    {% breadcrumb _('Messages') 'main:messages' %}
    {% breadcrumb message.subject '' %}
{% endblock %}

{% block content %}
    {% card 'message_card' _('Your Message') %}
        <table style="width: 100%;">
            <tr style="box-shadow: 2px 2px 2px 1px rgba(0, 0, 0, 0.2);">
                <td style="border: 1px solid black; padding: 5px; font-weight: bold; background: #DCDCDC">{{ message.subject }}</td>
            </tr>
            <tr style="box-shadow: 2px 2px 2px 1px rgba(0, 0, 0, 0.2);">
                <td style="border: 1px solid black; padding: 5px;">{{ message.message|safe|linebreaksbr }}</td>
            </tr>
            <tr>
                <td>
                    <br/>
                    {% if message_type == 'message' %}
                    <a href="{% url 'main:messages_reply' message.id %}" class="btn btn-primary">{% translate 'Reply' %}</a> &nbsp;
                    {% endif %}
                    <a href="{% url 'main:messages' %}" class="btn btn-primary">{% translate 'Go to Inbox' %}</a> &nbsp;
                    <a href="{% url 'main:messages_mark_unread' message_type message.id %}" class="btn btn-primary">{% translate 'Mark Unread' %}</a> &nbsp;
                    <button class="btn btn-danger" type="button" id="do-delete">{% translate 'Delete Message' %}</button>
                </td>
            </tr>
        </table>
    {% endcard %}

    {% include "bsmodals/confirm.html" %}
    {% include 'main/confirm_delete.html' %}
{% endblock %}

{% block extrascripts %}
    <script src="{% static 'bsmodals/bsmodals.js' %}"></script>
    <script>
        $(document).on('click', '.confirm-delete', function () {
            $("#confirmDeleteModal").attr("caller-id", $(this).attr("id"));
        });
        $(document).on('click', '#confirmDeleteButtonModal', function () {
            var caller = $("#confirmDeleteButtonModal").closest(".modal").attr("caller-id");
            window.location = $("#".concat(caller)).attr("href");
        });

        $(document).ready(function() {
            $('#do-delete').click(function () {
                bsmodals_confirm('Delete message?', ' Delete message? This cannot be undone.', (result) => {
                    if (result) {
                        location.href="{% url 'main:messages_delete' message_type message.id %}"
                    }
                }, yes_text = "Delete", yes_style = "btn-danger", no_text = "Cancel", no_style = "btn-primary");
            });
        });


    </script>
{% endblock %}

main/templates/main/users/request_username_done.html
{% extends 'main/base.html' %}
{% load i18n %}
{% load transcriptiones %}
{% load django_bootstrap_breadcrumbs %}

{% block page_title %}
    {% translate 'Username Request' %}
{%  endblock %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb _("Request Username") "" %}
{% endblock %}

{% block content %}

    {% card 'request_done_card' _('Your Username Has Been Reset') %}
        <div class="text-center">
            <p>{% translate 'Your username has been sent to you successfully.' %}</p>
            <a href="{% url 'main:login' %}" class="btn btn-primary">{% translate 'Login' %}</a>
        </div>
    {% endcard %}

{% endblock %}

main/templates/main/users/signup.html
{% extends 'main/base.html' %}
{% load static %}
{% load i18n %}
{% load transcriptiones %}
{% load crispy_forms_tags %}
{% load django_bootstrap_breadcrumbs %}

{% block page_title %}
    {% translate 'Registration' %}
{%  endblock %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb _("Registration") "" %}
{% endblock %}

{% block content %}
    {% card 'signup_card' _('Registration') %}
        {% if user.is_authenticated %}
            <p>{% translate 'You are already signed in.' %}</p>
            <div id="logout">
                <a class="btn btn-secondary" href="{% url 'main:logout' %}">{% translate 'Logout' %}</a>
            </div>
        {% else %}

                {% crispy form %}


        {% endif %}
    {% endcard %}
{% endblock %}

main/templates/main/users/update_user.html
{% extends 'main/base.html' %}
{% load static %}
{% load i18n %}
{% load transcriptiones %}
{% load crispy_forms_tags %}
{% load django_bootstrap_breadcrumbs %}

{% block page_title %}
    {% translate 'Change User Profile' %}
{%  endblock %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Users" "" %}
    {% breadcrumb request.user.username "main:profile" %}
    {% breadcrumb _('Update Profile') '' %}
{% endblock %}

{% block content %}

    {% include 'main/users/user_options.html' %}

    {% card 'update_user' _('Update Your User Information') %}
        <form method="post" action="{% url 'main:user_update' %}">
            {% csrf_token %}
            {% crispy form %}
        </form>
    {% endcard %}

{% endblock %}