main/urls.py
from django.conf.urls import url
from django.urls import path, include
from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView, PasswordChangeDoneView, PasswordResetDoneView,\
    PasswordResetCompleteView

import main.views.views_error
from main.views.views_upload_old import batch_upload
import main.views.views_admin as v_admin
import main.views.views_autocomplete as v_autocomplete
import main.views.views_browse as v_browse
import main.views.views_edit as v_edit
import main.views.views_export as v_export
import main.views.views_info as v_info
import main.views.views_messages as v_messages
import main.views.views_news as v_news
import main.views.views_search as v_search
import main.views.views_subscriptions as v_subscriptions
import main.views.views_upload as v_upload
import main.views.views_user as v_user
import main.views.views_api as v_api


app_name = 'main'
urlpatterns = [
    # ROOT VIEW
    path('', v_info.start_view, name='start'),
    path('set_language/<str:language>/', v_info.set_language_view, name='set_tr_language'),

    ##############
    # INFO PAGES
    path('info/', TemplateView.as_view(template_name='main/info/blank.html'), name='info'),
    path('info/instructions/', v_info.guidelines_view, name='guidelines'),
    path('info/tos/',        TemplateView.as_view(template_name='main/info/tos.html'),        name='tos'),
    path('info/about/',      TemplateView.as_view(template_name='main/info/about.html'),      name='about'),
    path('info/contact/', v_info.contact_view, name='contact'),
    path('info/faq/', TemplateView.as_view(template_name='main/info/faq.html'), name='faq'),
    path('info/unsubscribe/', v_info.unsubsribe_newsletter_view, name='unsubscribe_newsletter'),

    ##############
    # SEARCH VIEW
    # path('search/', v_search.SearchView.as_view(), name='search'),
    path('search/', v_search.transcriptiones_search, name='search'),
    path('search_redirect/', v_search.search_box_redirect, name='search_redirect'),

    ##############
    # News VIEW
    path('news/', v_news.news_view, name='news'),

    ##############
    # UPLOAD PAGES
    path('upload/options/', v_upload.upload_options, name='upload_options'),
    # Upload form for a new document
    path('upload/document/', v_upload.upload_transcription_view, name='upload_document'),
    # Upload form for a new document
    # path('upload/documents/', v_upload.upload_multiple_transcriptions_view, name='upload_multiple'),
    # Contact form for a batch upload
    path('upload/batch/', v_upload.upload_batch_view, name='upload_batch'),
    # Thank you screen after uploading
    path('upload/thanks/<int:doc_id>', v_upload.thanks_view, name='thank_you'),

    ##############
    # AUTOCOMPLETE VIEWS
    url(r'^inst-autocomplete/$', v_autocomplete.InstitutionAutocomplete.as_view(), name='inst-autocomplete', ),
    path('inst-autocomplete-id/', v_autocomplete.institution_id_view, name='inst-autocomplete-id', ),
    url(r'^refn-autocomplete/$', v_autocomplete.RefNumberAutocomplete.as_view(), name='refn-autocomplete', ),
    path('refn-autocomplete-id/', v_autocomplete.refnumber_id_view, name='refn-autocomplete-id', ),
    url(r'^srctype-autocomplete/$', v_autocomplete.SourceTypeAutocomplete.as_view(), name='srctype-autocomplete', ),
    url(r'^srctype-ch-autocomplete/$', v_autocomplete.SourceTypeChildAutocomplete.as_view(), name='srctype-ch-autocomplete', ),
    url(r'^author-autocomplete/$', v_autocomplete.AuthorAutocomplete.as_view(create_field='author_name'), name='author-autocomplete', ),
    url(r'^language-autocomplete/$', v_autocomplete.LanguageAutocomplete.as_view(), name='language-autocomplete', ),

    ##############
    # VIEW DATA PAGES
    path('display/', v_browse.browse_options, name='browse_options'),

    path('display/institutions/', v_browse.InstitutionListView.as_view(), name='institution_list'),
    path('display/institutions/<slug:inst_slug>/', v_browse.InstitutionDetailView.as_view(), name='institution_detail'),
    path('display/institutions/<slug:inst_slug>/<slug:ref_slug>/', v_browse.RefNumberDetailView.as_view(), name='ref_number_detail'),
    path('display/institutions/<slug:inst_slug>/<slug:ref_slug>/<slug:doc_slug>/', v_browse.DocumentDetailView.as_view(), name='document_detail'),
    path('display/institutions/<slug:inst_slug>/<slug:ref_slug>/<slug:doc_slug>/<int:version_nr>/', v_browse.DocumentDetailView.as_view(), name='document_legacy_detail'),
    path('display/institutions/<slug:inst_slug>/<slug:ref_slug>/<slug:doc_slug>/history/', v_browse.DocumentHistoryView.as_view(), name='document_history'),
    path('display/institutions/<slug:inst_slug>/<slug:ref_slug>/<slug:doc_slug>/export/', v_export.DocumentExportView.as_view(), name='document_export'),

    path('display/source_types/', v_browse.source_type_list_view, name='source_type_list'),
    path('display/source_types/<int:pk>/', v_browse.source_type_detail_view, name='source_type_detail'),
    path('display/source_types/<int:pk>/all/', v_browse.source_type_group_detail_view, name='source_type_group_detail'),

    path('display/scribes/', v_browse.AuthorListView.as_view(), name='author_list'),
    path('display/scribes/<int:pk>/', v_browse.AuthorDetailView.as_view(), name='author_detail'),

    path('insti_idx/', v_upload.upload_transcription_view, name='index_inst'),
    path('instis/create/', v_upload.ModalCreateInstitutionView.as_view(), name='create_inst'),
    path('refis/create/', v_upload.ModalCreateRefNumberView.as_view(), name='create_refn'),
    path('instis/', v_upload.institution_dropdown_view, name='insts'),
    path('refis/', v_upload.refnumber_dropdown_view, name='refns'),

    ##############
    # USER VIEWS
    path('user/signup/', v_user.signup, name='signup'),
    path('user/activationsent/', v_user.AccountActivationSentView.as_view(), name='account_activation_sent'),
    path('user/activate/<uidb64>/<token>/', v_user.show_activation_page, name='activate'),
    path('user/activate/', v_user.activate, name='activate_user'),
    path('user/login/', v_user.CustomLoginView.as_view(), name='login'),
    path('user/logout/', LogoutView.as_view(template_name='main/users/logout.html'), name='logout'),
    path('user/passwordchange/', v_user.CustomPasswordChangeView.as_view(), name='password_change'),
    path('user/passwordchange/done/', PasswordChangeDoneView.as_view(template_name='main/users/password_change_done.html'), name='password_change_done'),
    path('user/profile/', v_user.userprofile, name='profile'),
    path('user/documents/', v_user.my_documents, name='my_documents'),
    path('user/documents/created/', v_user.my_documents, name='my_own_documents'),
    path('user/documents/drafts/', v_user.my_documents, name='my_document_drafts'),
    path('user/public/profile/<str:username>/', v_user.public_profile, name='public_profile'),
    path('user/profile/update/', v_user.UserUpdateView.as_view(), name='user_update'),
    path('user/profile/email_update/', v_user.change_email_view, name='user_email_update'),
    path('user/passwordreset/', v_user.CustomPasswordResetView.as_view(), name='password_reset'),
    path('user/passwordreset/done/', PasswordResetDoneView.as_view(template_name='main/users/password_reset_done.html'), name='password_reset_done'),
    path('user/reset/<uidb64>/<token>/', v_user.CustomPasswordConfirmView.as_view(), name='password_reset_confirm'),
    path('user/reset/done/', PasswordResetCompleteView.as_view(template_name='main/users/password_reset_complete.html'), name='password_reset_complete'),
    path('user/usernamerequest/', v_user.request_username_view, name='username_request'),
    path('user/usernamerequest/done', v_user.request_username_done_view, name='username_request_done'),
    path('user/emailchange/done', v_user.request_email_change_done_view, name='change_email_request_done'),

    ##############
    # USER SUBSCRIPTIONS
    path('user/subscriptions/', v_subscriptions.subscriptions, name='subscriptions'),
    path('subscribe/institution/<int:pk>/', v_subscriptions.subscribe_institution_view, name='subscribe_institution'),
    path('subscribe/ref_number/<int:pk>/', v_subscriptions.subscribe_ref_number_view, name='subscribe_ref_number'),
    path('subscribe/document/<int:pk>/', v_subscriptions.subscribe_document_view, name='subscribe_document'),
    path('subscribe/user/<int:pk>/', v_subscriptions.subscribe_user_view, name='subscribe_user'),
    path('subscribe/scribe/<int:pk>/', v_subscriptions.subscribe_author_view, name='subscribe_author'),
    path('unsubscribe/institution/<int:pk>/', v_subscriptions.unsubscribe_institution_view, name='unsubscribe_institution'),
    path('unsubscribe/ref_number/<int:pk>/', v_subscriptions.unsubscribe_ref_number_view, name='unsubscribe_ref_number'),
    path('unsubscribe/document/<int:pk>/', v_subscriptions.unsubscribe_document_view, name='unsubscribe_document'),
    path('unsubscribe/user/<int:pk>/', v_subscriptions.unsubscribe_user_view, name='unsubscribe_user'),
    path('unsubscribe/scribe/<int:pk>/', v_subscriptions.unsubscribe_author_view, name='unsubscribe_author'),
    path('unsubscribe/all/', v_subscriptions.unsubscribe_all_view, name='unsubscribe_all'),

    ##############
    # USER MESSAGES & NOTIFICATIONS
    path('user/messages/', v_messages.messages_view, name='messages'),
    path('user/messages/delete/all', v_messages.delete_all_messages_view, name='messages_delete_all'),
    path('user/messages/delete/<str:message_type>/<int:message_id>', v_messages.messages_delete_view, name='messages_delete'),
    path('user/messages/view/<str:message_type>/<int:message_id>/', v_messages.messages_read_view, name='messages_read'),
    path('user/messages/reply/<int:message_id>/', v_messages.messages_reply_view, name='messages_reply'),
    path('user/messages/unread/<str:message_type>/<int:message_id>/', v_messages.messages_mark_unread_view, name='messages_mark_unread'),

transcriptiones/urls.py
"""transcriptiones URL Configuration
1. '' points to the main transcriptiones web app
2. 'admin' points to the Django administration interface
3. 'i18n' points to the language selection views

"""
from django.contrib import admin
from django.urls import include, path

handler404 = 'main.views.views_error.custom_page_not_found_view'
handler500 = 'main.views.views_error.custom_error_view'
handler403 = 'main.views.views_error.custom_permission_denied_view'
handler400 = 'main.views.views_error.custom_bad_request_view'

urlpatterns = [
    path('',  include('main.urls')),
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    ]

templates/base.html
{% load static %}
{% load i18n %}
{% load django_bootstrap_breadcrumbs %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="TRANSCRIPTIONES"> <!-- TODO Add description, keywords -->
        <meta name="author" content="TRANSCRIPTIONES">

        <title>{% block title_bar %}TRANSCRIPTIONES{% endblock %}</title>
        <link rel="shortcut icon" href="{% static 'main/images/favicon.ico' type='image/x-icon' %}">

        <!-- Bootstrap core JavaScript -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>

        <!-- Plugin JavaScript -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>

        <!-- Bootstrap Core CSS -->
        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet">

        <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">

        <!-- Custom scripts for this template -->
        <script type="text/javascript" src="{% static 'main/js/transcriptiones.js' %}"></script>

        <!-- Fontawesome: included as django module -->
        <link href="{% static 'fontawesome/css/all.min.css' %}" rel="stylesheet" type="text/css">
        <script src="{% static 'fontawesome/js/all.min.js' %}"></script>

        <!-- simple-line-icons: Used for social media icons in footer -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.4.1/css/simple-line-icons.css">

        <!-- Flags for country dropdown -->
        <link rel="stylesheet" href="{% static 'flags/sprite.css' %}">

        <!-- Custom CSS -->

        {%  block custom_css %}
            <link rel="stylesheet" type="text/css" href="{% static 'main/css/transcriptiones.css' %}">
            <link rel="stylesheet" type="text/css" href="{% static 'main/css/sidebar.css' %}">
        {% endblock %}
        {% block additional_css %}
        {% endblock additional_css %}

        {% block additional_head_tags %}
        {% endblock additional_head_tags %}
    </head>

    <body id="page-top">
        {% block body_includes %}
        {% endblock %}

        {% block breadcrumb_init %}
        {% endblock %}
        <!-- Navigation -->
        <nav class="navbar navbar-expand-sm fixed-top position-absolute text.navbar">
            <ul class="navbar-nav align-items-center">
                <li class="navbar-brand">
                    <a class="nav-link text-navbar" href="{% url 'main:start' %}">Logo</a>
                </li>
                <li class="navbar-nav-item d-none d-sm-block">
                    <a class="nav-link text-navbar" href="{% url 'main:upload_document' %}">{% translate 'Upload' %}</a>
                </li>
                <li class="navbar-nav-item d-none d-sm-block">
                    <a class="nav-link text-navbar" href="{% url 'main:institution_list' %}">{% translate 'Browse' %}</a>
                </li>
                <li class="navbar-nav-item d-none d-sm-block">
                    <a class="nav-link text-navbar" href="{% url 'main:search' %}">{% translate 'Search' %}</a>
                </li>
                <li class="navbar-nav-item d-none d-sm-block">
                    {% if user.is_authenticated %}
                        <a class="nav-link text-navbar" href="{% url 'main:logout' %}">{% translate 'Logout' %}</a>
                    {% else %}
                        <a class="nav-link text-navbar" href="{% url 'main:login' %}">{% translate 'Login' %}</a>
                    {% endif %}
                </li>
            </ul>
        </nav>

         <!-- Sidebar -->
        {% include "sidebar.html" %}

        <!-- Content -->
        {% block base_content %}
            <section class="content-section bg-white">
                <div class="container text-center">
                    <div class="row">
                        <div class="col-sm-10 mx-auto">
                            {%  block breadcrumbs %}
                                {% render_breadcrumbs %}
                            {% endblock %}
                            <div class="content-section-heading">
                                <h2 class="mb-5">
                                    {% block page_title %}
                                        Implement block "page_title"
                                    {% endblock %}
                                </h2>
                            </div>
                            <div>
                                {% for message in messages %}
                  <div class="alert {{ message.tags }}" role="alert" >
                    <small>{{ message }}</small>
                  </div>
                {% endfor %}

                {% if form.non_field_errors %}
                  <div class="alert alert-danger" role="alert">
                      <small>{{ form.non_field_errors }}</small>
                  </div>
                {% endif %}
                            </div>
                            {% block content %}
                                    <p class="lead mb-5">Implement block "content"</p>
                                {% endblock %}

                        </div>
                    </div>
                </div>
            </section>
        {% endblock %}


    <!-- Footer -->
    <footer class="footer text-center">
        <div class="container">
            <ul class="list-inline mb-5">
                <li class="list-inline-item">
                    <a class="social-link rounded-circle text-white mr-3" href="#">
                        <i class="icon-social-facebook"></i>
                    </a>
                </li>
                <li class="list-inline-item">
                    <a class="social-link rounded-circle text-white mr-3" href="#">
                        <i class="icon-social-twitter"></i>
                    </a>
                </li>
                <li class="list-inline-item">
                    <a class="social-link rounded-circle text-white" href="#">
                        <i class="icon-social-github"></i>
                    </a>
                </li>
            </ul>
            <p class="text-muted small mb-0">Copyright &copy; TRANSCRIPTIONES 2020</p> <!-- TODO Get these values from a context processor-->
        </div>

        <!-- Sidebar -->
        {% include "language.html" %}
    </footer>

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded js-scroll-trigger" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    {% block javascript %}
    {% endblock javascript %}
</body>
</html>

templates/toolbox.html
{% load static %}
{% load i18n %}

<div class="btn-group-vertical">
    <a class="btn btn-light btn-rounded" id="toolboxicon" title={% translate 'Edit Transcription' %}
       href="{% url 'main:edit_transcript' document.parent_ref_number.holding_institution.institution_slug document.parent_ref_number.ref_number_slug document.document_slug %}">
        <img src="{% static 'main/images/check-double-solid-t.png' %}" alt="icon" id="toolboximage" width="38" height="18" />
    </a>

    <a class="btn btn-light btn-rounded" id="toolboxicon" title="{% translate 'Edit Metadata' %}"
       href="{% url 'main:edit_meta' document.parent_ref_number.holding_institution.institution_slug document.parent_ref_number.ref_number_slug document.document_slug %}">
        <img src="{% static 'main/images/check-double-solid-m.png' %}" alt="icon" id="toolboximage" width="38" height="18" />
    </a>

    <a class="btn btn-light btn-rounded" id="toolboxicon" title="{% translate 'Versions' %}"
       href="{% url 'main:document_history' document.parent_ref_number.holding_institution.institution_slug document.parent_ref_number.ref_number_slug document.document_slug %}">
        <i class="fas fa-code-branch"></i>
    </a>

    <a class="btn btn-light btn-rounded" id="toolboxicon" title="{% translate 'Export' %}">
        <i class="fas fa-file-export"></i>
    </a>
</div>