main/urls.py
from django.conf.urls import url
from django.urls import path, include
from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView, PasswordChangeDoneView, PasswordResetDoneView,\
    PasswordResetCompleteView

import main.views.views_error
from main.views.views_upload_old import batch_upload
import main.views.views_admin as v_admin
import main.views.views_autocomplete as v_autocomplete
import main.views.views_browse as v_browse
import main.views.views_edit as v_edit
import main.views.views_export as v_export
import main.views.views_info as v_info
import main.views.views_messages as v_messages
import main.views.views_news as v_news
import main.views.views_search as v_search
import main.views.views_subscriptions as v_subscriptions
import main.views.views_upload as v_upload
import main.views.views_user as v_user
import main.views.views_api as v_api


app_name = 'main'
urlpatterns = [
    # ROOT VIEW
    path('', v_info.start_view, name='start'),
    path('set_language/<str:language>/', v_info.set_language_view, name='set_tr_language'),

    ##############
    # INFO PAGES
    path('info/', TemplateView.as_view(template_name='main/info/blank.html'), name='info'),
    path('info/instructions/', v_info.guidelines_view, name='guidelines'),
    path('info/tos/',        TemplateView.as_view(template_name='main/info/tos.html'),        name='tos'),
    path('info/about/',      TemplateView.as_view(template_name='main/info/about.html'),      name='about'),
    path('info/contact/', v_info.contact_view, name='contact'),
    path('info/faq/', TemplateView.as_view(template_name='main/info/faq.html'), name='faq'),
    path('info/unsubscribe/', v_info.unsubsribe_newsletter_view, name='unsubscribe_newsletter'),

    ##############
    # SEARCH VIEW
    # path('search/', v_search.SearchView.as_view(), name='search'),
    path('search/', v_search.transcriptiones_search, name='search'),
    path('search_redirect/', v_search.search_box_redirect, name='search_redirect'),

    ##############
    # News VIEW
    path('news/', v_news.news_view, name='news'),

    ##############
    # UPLOAD PAGES
    path('upload/options/', v_upload.upload_options, name='upload_options'),
    # Upload form for a new document
    path('upload/document/', v_upload.upload_transcription_view, name='upload_document'),
    # Upload form for a new document
    # path('upload/documents/', v_upload.upload_multiple_transcriptions_view, name='upload_multiple'),
    # Contact form for a batch upload
    path('upload/batch/', v_upload.upload_batch_view, name='upload_batch'),
    # Thank you screen after uploading
    path('upload/thanks/<int:doc_id>', v_upload.thanks_view, name='thank_you'),

    ##############
    # AUTOCOMPLETE VIEWS
    url(r'^inst-autocomplete/$', v_autocomplete.InstitutionAutocomplete.as_view(), name='inst-autocomplete', ),
    path('inst-autocomplete-id/', v_autocomplete.institution_id_view, name='inst-autocomplete-id', ),
    url(r'^refn-autocomplete/$', v_autocomplete.RefNumberAutocomplete.as_view(), name='refn-autocomplete', ),
    path('refn-autocomplete-id/', v_autocomplete.refnumber_id_view, name='refn-autocomplete-id', ),
    url(r'^srctype-autocomplete/$', v_autocomplete.SourceTypeAutocomplete.as_view(), name='srctype-autocomplete', ),
    url(r'^srctype-ch-autocomplete/$', v_autocomplete.SourceTypeChildAutocomplete.as_view(), name='srctype-ch-autocomplete', ),
    url(r'^author-autocomplete/$', v_autocomplete.AuthorAutocomplete.as_view(create_field='author_name'), name='author-autocomplete', ),
    url(r'^language-autocomplete/$', v_autocomplete.LanguageAutocomplete.as_view(), name='language-autocomplete', ),

    ##############
    # VIEW DATA PAGES
    path('display/', v_browse.browse_options, name='browse_options'),

    path('display/institutions/', v_browse.InstitutionListView.as_view(), name='institution_list'),
    path('display/institutions/<slug:inst_slug>/', v_browse.InstitutionDetailView.as_view(), name='institution_detail'),
    path('display/institutions/<slug:inst_slug>/<slug:ref_slug>/', v_browse.RefNumberDetailView.as_view(), name='ref_number_detail'),
    path('display/institutions/<slug:inst_slug>/<slug:ref_slug>/<slug:doc_slug>/', v_browse.DocumentDetailView.as_view(), name='document_detail'),
    path('display/institutions/<slug:inst_slug>/<slug:ref_slug>/<slug:doc_slug>/<int:version_nr>/', v_browse.DocumentDetailView.as_view(), name='document_legacy_detail'),
    path('display/institutions/<slug:inst_slug>/<slug:ref_slug>/<slug:doc_slug>/history/', v_browse.DocumentHistoryView.as_view(), name='document_history'),
    path('display/institutions/<slug:inst_slug>/<slug:ref_slug>/<slug:doc_slug>/export/', v_export.DocumentExportView.as_view(), name='document_export'),

    path('display/source_types/', v_browse.source_type_list_view, name='source_type_list'),
    path('display/source_types/<int:pk>/', v_browse.source_type_detail_view, name='source_type_detail'),
    path('display/source_types/<int:pk>/all/', v_browse.source_type_group_detail_view, name='source_type_group_detail'),

    path('display/scribes/', v_browse.AuthorListView.as_view(), name='author_list'),
    path('display/scribes/<int:pk>/', v_browse.AuthorDetailView.as_view(), name='author_detail'),

    path('insti_idx/', v_upload.upload_transcription_view, name='index_inst'),
    path('instis/create/', v_upload.ModalCreateInstitutionView.as_view(), name='create_inst'),
    path('refis/create/', v_upload.ModalCreateRefNumberView.as_view(), name='create_refn'),
    path('instis/', v_upload.institution_dropdown_view, name='insts'),
    path('refis/', v_upload.refnumber_dropdown_view, name='refns'),

    ##############
    # USER VIEWS
    path('user/signup/', v_user.signup, name='signup'),
    path('user/activationsent/', v_user.AccountActivationSentView.as_view(), name='account_activation_sent'),
    path('user/activate/<uidb64>/<token>/', v_user.show_activation_page, name='activate'),
    path('user/activate/', v_user.activate, name='activate_user'),
    path('user/login/', v_user.CustomLoginView.as_view(), name='login'),
    path('user/logout/', LogoutView.as_view(template_name='main/users/logout.html'), name='logout'),
    path('user/passwordchange/', v_user.CustomPasswordChangeView.as_view(), name='password_change'),
    path('user/passwordchange/done/', PasswordChangeDoneView.as_view(template_name='main/users/password_change_done.html'), name='password_change_done'),
    path('user/profile/', v_user.userprofile, name='profile'),
    path('user/documents/', v_user.my_documents, name='my_documents'),
    path('user/documents/created/', v_user.my_documents, name='my_own_documents'),
    path('user/documents/drafts/', v_user.my_documents, name='my_document_drafts'),
    path('user/public/profile/<str:username>/', v_user.public_profile, name='public_profile'),
    path('user/profile/update/', v_user.UserUpdateView.as_view(), name='user_update'),
    path('user/profile/email_update/', v_user.change_email_view, name='user_email_update'),
    path('user/passwordreset/', v_user.CustomPasswordResetView.as_view(), name='password_reset'),
    path('user/passwordreset/done/', PasswordResetDoneView.as_view(template_name='main/users/password_reset_done.html'), name='password_reset_done'),
    path('user/reset/<uidb64>/<token>/', v_user.CustomPasswordConfirmView.as_view(), name='password_reset_confirm'),
    path('user/reset/done/', PasswordResetCompleteView.as_view(template_name='main/users/password_reset_complete.html'), name='password_reset_complete'),
    path('user/usernamerequest/', v_user.request_username_view, name='username_request'),
    path('user/usernamerequest/done', v_user.request_username_done_view, name='username_request_done'),
    path('user/emailchange/done', v_user.request_email_change_done_view, name='change_email_request_done'),

    ##############
    # USER SUBSCRIPTIONS
    path('user/subscriptions/', v_subscriptions.subscriptions, name='subscriptions'),
    path('subscribe/institution/<int:pk>/', v_subscriptions.subscribe_institution_view, name='subscribe_institution'),
    path('subscribe/ref_number/<int:pk>/', v_subscriptions.subscribe_ref_number_view, name='subscribe_ref_number'),
    path('subscribe/document/<int:pk>/', v_subscriptions.subscribe_document_view, name='subscribe_document'),
    path('subscribe/user/<int:pk>/', v_subscriptions.subscribe_user_view, name='subscribe_user'),
    path('subscribe/scribe/<int:pk>/', v_subscriptions.subscribe_author_view, name='subscribe_author'),
    path('unsubscribe/institution/<int:pk>/', v_subscriptions.unsubscribe_institution_view, name='unsubscribe_institution'),
    path('unsubscribe/ref_number/<int:pk>/', v_subscriptions.unsubscribe_ref_number_view, name='unsubscribe_ref_number'),
    path('unsubscribe/document/<int:pk>/', v_subscriptions.unsubscribe_document_view, name='unsubscribe_document'),
    path('unsubscribe/user/<int:pk>/', v_subscriptions.unsubscribe_user_view, name='unsubscribe_user'),
    path('unsubscribe/scribe/<int:pk>/', v_subscriptions.unsubscribe_author_view, name='unsubscribe_author'),
    path('unsubscribe/all/', v_subscriptions.unsubscribe_all_view, name='unsubscribe_all'),

    ##############
    # USER MESSAGES & NOTIFICATIONS
    path('user/messages/', v_messages.messages_view, name='messages'),
    path('user/messages/delete/all', v_messages.delete_all_messages_view, name='messages_delete_all'),
    path('user/messages/delete/<str:message_type>/<int:message_id>', v_messages.messages_delete_view, name='messages_delete'),
    path('user/messages/view/<str:message_type>/<int:message_id>/', v_messages.messages_read_view, name='messages_read'),
    path('user/messages/reply/<int:message_id>/', v_messages.messages_reply_view, name='messages_reply'),
    path('user/messages/unread/<str:message_type>/<int:message_id>/', v_messages.messages_mark_unread_view, name='messages_mark_unread'),

transcriptiones/urls.py
"""transcriptiones URL Configuration
1. '' points to the main transcriptiones web app
2. 'admin' points to the Django administration interface
3. 'i18n' points to the language selection views

"""
from django.contrib import admin
from django.urls import include, path

handler404 = 'main.views.views_error.custom_page_not_found_view'
handler500 = 'main.views.views_error.custom_error_view'
handler403 = 'main.views.views_error.custom_permission_denied_view'
handler400 = 'main.views.views_error.custom_bad_request_view'

urlpatterns = [
    path('',  include('main.urls')),
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    ]

main/forms/forms_edit.py
"""forms_admin contains all Form classes used to edit documents. There are separate forms to
edit the meta data and the transcription itself"""
from dal import autocomplete
from django import forms
from django.urls import reverse
from django.utils.safestring import mark_safe
from django.utils.text import format_lazy

from main.forms.forms_helper import initialize_form_helper, get_popover_html, get_clean_partial_date
from main.models import Document, Author, Language, SourceType
from django.utils.translation import ugettext_lazy as _


class EditTranscriptionForm(forms.ModelForm):
    """This is the edit form for the transcription part of a document."""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = initialize_form_helper()
        tos_url = reverse('main:tos')
        self.fields['accept_tos'] = forms.BooleanField(
            label=_('Accept Terms of Service'),
            required=True,
            help_text=mark_safe(
                _('In order to commit your changes you are required to accept the %s and agree that '
                  'all uploaded transcriptions will be will be subject to a %s.') %
                (format_lazy('<a href="{tos_url}" target="_blank" rel="noopener noreferrer">{tos_text}</a>', tos_url=tos_url, tos_text=_('terms of service')),
                 _('<a href="https://creativecommons.org/share-your-work/public-domain/cc0/" target="_blank" rel="noopener noreferrer">CC0 licence</a>'))))

    class Meta:
        model = Document
        fields = ('transcription_text', 'transcription_scope', 'commit_message', 'publish_user')

        labels = {
            'transcription_scope': get_popover_html(Document, 'transcription_scope'),
            'commit_message': get_popover_html(Document, 'commit_message'),
            'publish_user': get_popover_html(Document, 'publish_user'),
        }


class EditMetaForm(forms.ModelForm):
    """This is the edit form for the meta part of a document."""

    selection_helper_source_type = forms.ModelChoiceField(
                                        label=_('First level Source Type'),
                                        queryset=SourceType.objects.filter(parent_type=None).order_by('type_name'),
                                        widget=autocomplete.ModelSelect2(url='main:srctype-autocomplete',
                                                                         attrs={'data-html': True}))

    source_type = forms.ModelChoiceField(queryset=SourceType.objects.exclude(parent_type=None).order_by('type_name'),
                                         widget=autocomplete.ModelSelect2(url='main:srctype-ch-autocomplete',
                                                                          forward=['selection_helper_source_type', ],
                                                                          attrs={'data-html': True}))

    author = forms.ModelMultipleChoiceField(queryset=Author.objects.all().order_by('author_name'),
                                            widget=autocomplete.ModelSelect2Multiple(url='main:author-autocomplete'),
                                            required=True)

    language = forms.ModelMultipleChoiceField(queryset=Language.objects.all().order_by('name_native'),
                                              widget=autocomplete.ModelSelect2Multiple(
                                                  url='main:language-autocomplete'),
                                              required=True)

    seal = forms.NullBooleanField(label=get_popover_html(Document, 'seal'),
                                  help_text=Document._meta.get_field("seal").help_text,
                                  widget=forms.Select(
                                      choices=[('', _('(Unknown)')), (True, _('Yes')), (False, _('No'))]),
                                  required=False)

    illuminated = forms.NullBooleanField(label=get_popover_html(Document, 'illuminated'),
                                         help_text=Document._meta.get_field("illuminated").help_text,
                                         widget=forms.Select(
                                             choices=[('', _('(Unknown)')), (True, _('Yes')), (False, _('No'))]),
                                         required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = initialize_form_helper()
        tos_url = reverse('main:tos')
        self.fields['accept_tos'] = forms.BooleanField(
            label=_('Accept Terms of Service'),
            required=True,
            help_text=mark_safe(
                _('In order to commit your changes you are required to accept the %s and agree that '
                  'all uploaded transcriptions will be will be subject to a %s.') %
                (format_lazy('<a href="{tos_url}" target="_blank" rel="noopener noreferrer">{tos_text}</a>', tos_url=tos_url, tos_text=_('terms of service')),
                 _('<a href="https://creativecommons.org/share-your-work/public-domain/cc0/" target="_blank" rel="noopener noreferrer">CC0 licence</a>'))))

    def clean_doc_start_date(self):
        data = self.cleaned_data['doc_start_date']
        new_data = get_clean_partial_date(data)
        return new_data

    def clean_doc_end_date(self):
        data = self.cleaned_data['doc_end_date']
        new_data = get_clean_partial_date(data)
        return new_data

    class Meta:
        model = Document
        exclude = ('title_name', 'parent_ref_number', 'transcription_text', 'institution_utc_add',
                   'document_slug', 'version_number', 'transcription_scope')

        labels = {
            'doc_start_date': get_popover_html(Document, 'doc_start_date'),
            'doc_end_date': get_popover_html(Document, 'doc_end_date'),
            'place_name': get_popover_html(Document, 'place_name'),
            'transcription_text': get_popover_html(Document, 'transcription_text'),
            'material': get_popover_html(Document, 'material'),
            'measurements_width': get_popover_html(Document, 'measurements_width'),
            'measurements_length': get_popover_html(Document, 'measurements_length'),
            'pages': get_popover_html(Document, 'pages'),
            'paging_system': get_popover_html(Document, 'paging_system'),
            # 'illuminated': get_popover_html(Document, 'illuminated'),
            # 'seal': get_popover_html(Document, 'seal'),
            'comments': get_popover_html(Document, 'comments'),
            'commit_message': get_popover_html(Document, 'commit_message'),
            'publish_user': get_popover_html(Document, 'publish_user'),
        }

main/views/views_error.py
from django.shortcuts import render


def custom_page_not_found_view(request, exception=None):
    return render(request, "main/errors/404.html", {})

def custom_error_view(request, exception=None):
    return render(request, "main/errors/500.html", {})

def custom_permission_denied_view(request, exception=None):
    return render(request, "main/errors/403.html", {})

def custom_bad_request_view(request, exception=None):
    return render(request, "main/errors/400.html", {})

main/templates/main/base_copy.html
{% load static %}
{% load i18n %}
{% load django_bootstrap_breadcrumbs %}

 {% get_current_language as LANGUAGE_CODE %}

<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="TRANSCRIPTIONES"> <!-- TODO Add description, keywords -->
        <meta name="author" content="TRANSCRIPTIONES">

        <title>{% block title_bar %}TRANSCRIPTIONES{% endblock %}</title>
        <link rel="shortcut icon" href="{% static 'main/images/favicon.ico' type='image/x-icon' %}">

        <!-- Bootstrap core JavaScript -->
        <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script> -->
        <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script> -->
        <script src="{% static 'assets/js/jquery-3.2.1.min.js' %}"></script>
        <script src="{% static 'assets/js/popper.min.js' %}"></script>
        <!-- <script src="{# static 'assets/js/bootstrap.min.js' #}"></script> -->
        <script src="{% static 'js/jquery.bootstrap.modal.forms.js' %}"></script>
        <script src="https://cdn.jsdelivr.net/gh/xcash/bootstrap-autocomplete@v2.3.7/dist/latest/bootstrap-autocomplete.min.js"></script>

        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>

        <!-- Plugin JavaScript -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>

        <!-- Bootstrap Core CSS -->
        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet">

        <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">

        <!-- Custom scripts for this template -->
        <script src="{% static 'main/js/transcriptiones.js' %}"></script>

        <!-- Fontawesome: included as django module -->
        <link href="{% static 'fontawesome/css/all.min.css' %}" rel="stylesheet" type="text/css">
        <script src="{% static 'fontawesome/js/all.min.js' %}"></script>

        <!-- simple-line-icons: Used for social media icons in footer -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.4.1/css/simple-line-icons.css">

        <!-- Flags for country dropdown -->
        <link rel="stylesheet" href="{% static 'flags/sprite.css' %}">

        <!-- Transcriptiones CSS -->
        <link rel="stylesheet" type="text/css" href="{% static 'main/css/transcriptiones_base.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'main/css/scroll_to_top.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'main/css/sidebar.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'main/css/footer.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'main/css/breadcrumbs.css' %}">

        {%  block custom_css %}
            <link rel="stylesheet" type="text/css" href="{% static 'main/css/transcriptiones.css' %}">
        {% endblock %}

        {% block additional_css %}
        {% endblock %}

        {% block additional_javascript %}
        {% endblock %}

        {% block additional_head_tags %}
        {% endblock %}


    {% block scripts %}

    {% endblock %}
    </head>

    <body id="page-top">
        {% block body_includes %}
        {% endblock %}

        {% block modal_includes %}
        {% endblock %}

        {% block breadcrumbs %}
            {% clear_breadcrumbs %}
            {% breadcrumb "Transcriptiones" "/" %}
        {% endblock %}

        <!-- Navigation -->
        <nav class="navbar navbar-expand-sm fixed-top position-absolute text.navbar">
            <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
                 <ul class="navbar-nav mr-auto align-items-center">
                    <li class="navbar-brand">
                        <a class="nav-link text-navbar" href="{% url 'main:start' %}">Logo</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle text-navbar" href="#" id="upload_dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                               {% translate 'Upload' %}
                        </a>
                        <div class="dropdown-menu" aria-labelledby="upload_dropdown">
                            <a class="dropdown-item" href="{% url 'main:upload_options' %}">{% translate 'Upload Options' %}</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'main:upload_document' %}">{% translate 'Upload Single Page' %}</a>
                            <a class="dropdown-item" href="{% url 'main:upload_multiple' %}">{% translate 'Upload Multiple Pages' %}</a>
                            <a class="dropdown-item" href="{% url 'main:upload_batch' %}">{% translate 'Guided Batch Upload' %}</a>
                        </div>
                    </li>
                    <!-- <li class="navbar-nav-item d-none d-sm-block"> -->
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle text-navbar" href="#" id="browse_dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                               {% translate 'Browse' %}
                        </a>
                        <div class="dropdown-menu" aria-labelledby="browse_dropdown">
                            <a class="dropdown-item" href="{% url 'main:browse_options' %}">{% translate 'Browse Options' %}</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'main:institution_list' %}">{% translate 'Institutions' %}</a>
                            <a class="dropdown-item" href="{% url 'main:source_type_list' %}">{% translate 'Source Types' %}</a>
                            <a class="dropdown-item" href="{% url 'main:author_list' %}">{% translate 'Authors' %}</a>
                        </div>
                    </li>
                    <li class="navbar-nav-item d-none d-sm-block">
                        <a class="nav-link text-navbar" href="{% url 'main:search' %}">{% translate 'Search' %}</a>
                    </li>
                    {% if not user.is_authenticated %}
                        <li class="navbar-nav-item d-none d-sm-block">
                            <a class="nav-link text-navbar" href="{% url 'main:login' %}">{% translate 'Login' %}</a>
                        </li>
                        <li class="navbar-nav-item d-none d-sm-block">
                            <a class="nav-link text-navbar" href="{% url 'main:signup' %}">{% translate 'Register' %}</a>
                        </li>
                     {% endif %}
                 </ul>
            </div>

            <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
                <ul class="navbar-nav ml-auto" style="margin-right: 70px;">
                    {% if user.is_authenticated %}

                        <li class="nav-item dropdown">
                            {% if user_subscriptions > 0 %}
                                <a href="{% url 'main:notifications' %}" title="You have {{ user_subscriptions }} notifications"><span class="badge badge-pill badge-danger">{{ user_subscriptions }}</span></a>
                            {% endif %}
                            {% if user_messages > 0 %}
                                <a href="{% url 'main:messages' %}" title="You have {{ user_messages }} messages"><span class="badge badge-pill badge-warning">{{ user_messages }}</span></a> &nbsp;
                            {% endif %}
                            <a class="nav-link dropdown-toggle text-navbar" href="#" id="user_dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-user"></i>
                            </a>
                            <div class="dropdown-menu" aria-labelledby="user_dropdown">
                                <a class="dropdown-item disabled" href="#"><small>{% translate 'Your Profile' %}</small></a>
                                <a class="dropdown-item" href="{% url 'main:my_documents' %}">{% translate 'My Documents' %}</a>
                                <a class="dropdown-item" href="{% url 'main:profile' %}">{% translate 'User Information' %}</a>
                                <a class="dropdown-item" href="{% url 'main:subscriptions' %}">{% translate 'Subscriptions' %}</a>
                                <a class="dropdown-item" href="{% url 'main:messages' %}">{% translate 'Inbox' %}</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item disabled" href="#"><small>{% translate 'Administrator Functions' %}</small></a>
                                <a class="dropdown-item" href="{% url 'main:admin' %}">{% translate 'Administration Pages' %}</a>
                                <a class="dropdown-item" href="{% url 'admin:index' %}">{% translate 'Django Admin' %}</a>
                              <div class="dropdown-divider"></div>
                              <a class="dropdown-item" href="{% url 'main:logout' %}">{% translate 'Logout' %}</a>
                            </div>
                        </li>
                    {% endif %}
                    <li style="margin-top: 12px;">{% include "main/search_box.html" %}</li>
                </ul>
            </div>
        </nav>
        {% include "main/sidebar.html" %}
        <!-- Content -->
        {% block base_content %}
            <section class="content-section">
                <div class="container text-center">
                   {% for message in messages %}
                      <div class="alert {{ message.tags }}" role="alert" >
                        <button type="button" class="close" data-dismiss="alert">×</button>
                        {{ message }}
                      </div>
                    {% endfor %}

                    <div class="row">
                        <div class="col-sm-10 mx-auto">
                            {% render_breadcrumbs %}
                            <div class="content-section-heading">
                                <h3 class="mb-sm-3">
                                    {% block page_title %}
                                        Implement block "page_title"
                                    {% endblock %}
                                </h3>
                            </div>
                            <div>
                            </div>
                            {% block content %}
                                    <p class="lead mb-5">Implement block "content"</p>
                                {% endblock %}
                        </div>
                    </div>
                </div>
            </section>
        {% endblock %}


    <!-- Footer -->
    <footer class="footer text-center">
        <div class="container">
            <ul class="list-inline mb-5">
                <li class="list-inline-item">
                    <a class="social-link rounded-circle text-white mr-3" href="#">
                        <i class="icon-social-facebook"></i>
                    </a>
                </li>
                <li class="list-inline-item">
                    <a class="social-link rounded-circle text-white mr-3" href="#">
                        <i class="icon-social-twitter"></i>
                    </a>
                </li>
                <li class="list-inline-item">
                    <a class="social-link rounded-circle text-white" href="#">
                        <i class="icon-social-github"></i>
                    </a>
                </li>
            </ul>
            <p class="text-muted small mb-0">Copyright &copy; TRANSCRIPTIONES 2021</p> <!-- TODO Get these values from a context processor-->
        </div>

        <!-- Sidebar -->
        {% include "main/language.html" %}
    </footer>

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded js-scroll-trigger" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    {% block extrascripts %}{% endblock extrascripts %}
    <script>
        $('.alert').hide().fadeIn(500).delay(4000).fadeOut(500);
    </script>
</body>
</html>